program iktan;
uses
  Forms,
  TLoggerUnit,
  SysUtils,
  URemovibles in 'movil\Removibles\URemovibles.pas' {FRemovibles},
  UIngreso in 'movil\Ingreso\UIngreso.pas' {FIngreso},
  UPrincipal in 'movil\Principal\UPrincipal.pas' {FPrincipal},
  CLibrerias in 'movil\Librerias\CLibrerias.pas',
  RLibrerias in 'movil\Librerias\RLibrerias.pas',
  UFormato in 'movil\Formato\UFormato.pas' {FFormato},
  CFormato in 'movil\Formato\CFormato.pas',
  RFormato in 'movil\Formato\RFormato.pas',
  UExtraerUsb in 'movil\Utilerias\UExtraerUsb.pas',
  GuidEx in 'movil\Utilerias\GuidEx.pas',
  UWifi in 'movil\Utilerias\UWifi.pas',
  UDml in 'movil\Xml\UDml.pas',
  CDml in 'movil\Xml\CDml.pas',
  URestauracion in 'movil\Restauracion\URestauracion.pas' {FRestauracion},
  TRestauracion in 'movil\Restauracion\TRestauracion.pas',
  CRestauracion in 'movil\Restauracion\CRestauracion.pas',
  UInterface in 'movil\Wifi\UInterface.pas' {FInterface},
  CInterface in 'movil\Wifi\CInterface.pas',
  UtilsWifiDemon in 'movil\Wifi\UtilsWifiDemon.pas',
  RXml in 'movil\Wifi\RXml.pas',
  UConectarInternet in 'movil\Wifi\UConectarInternet.pas' {FConectarInternet},
  XWifi in 'movil\Wifi\XWifi.pas',
  UEntrada in 'movil\Acceso\UEntrada.pas' {FEntrada},
  UTransparente in 'movil\Acceso\UTransparente.pas' {FTransparente},
  UFotografiaFiltro in 'movil\Fotos\UFotografiaFiltro.pas' {FFotografiaFiltro},
  UTomarFoto in 'movil\Fotos\UTomarFoto.pas' {FTomarFoto},
  TFotos in 'movil\Fotos\TFotos.pas',
  CFotos in 'movil\Fotos\CFotos.pas',
  UCorreo in 'movil\Correo\UCorreo.pas' {FCorreo},
  CCorreo in 'movil\Correo\CCorreo.pas',
  UContraseniaUsuarioAcciones in 'movil\ContraseniaUsuario\UContraseniaUsuarioAcciones.pas' {FContraseniaUsuarioAcciones},
  UContraseniaUsuario in 'movil\ContraseniaUsuario\UContraseniaUsuario.pas' {FContraseniaUsuario},
  TContraseniaUsuario in 'movil\ContraseniaUsuario\TContraseniaUsuario.pas',
  CContraseniaUsuario in 'movil\ContraseniaUsuario\CContraseniaUsuario.pas',
  RContraseniaUsuario in 'movil\ContraseniaUsuario\RContraseniaUsuario.pas',
  UCapturaPantalla in 'movil\CapturaPantalla\UCapturaPantalla.pas' {FCapturaPantalla},
  UTemas in 'movil\Temas\UTemas.pas' {FTemas},
  TTemas in 'movil\Temas\TTemas.pas',
  CTemas in 'movil\Temas\CTemas.pas',
  CRemovibles in 'movil\Removibles\CRemovibles.pas',
  UContrasenia in 'movil\Ingreso\UContrasenia.pas' {FContrasenia},
  TIngreso in 'movil\Ingreso\TIngreso.pas',
  CIngreso in 'movil\Ingreso\CIngreso.pas',
  TRespaldos in 'movil\Respaldos\TRespaldos.pas',
  CRespaldos in 'movil\Respaldos\CRespaldos.pas',
  URespaldos in 'movil\Respaldos\URespaldos.pas' {FRespaldos},
  UKioscoContenedor in 'movil\Kiosco\UKioscoContenedor.pas',
  TKiosco in 'movil\Kiosco\TKiosco.pas',
  CKioscoContenedor in 'movil\Kiosco\CKioscoContenedor.pas',
  RKiosco in 'movil\Kiosco\RKiosco.pas',
  UBaseTnx in 'movil\BD\UBaseTnx.pas',
  UModuls in 'movil\BD\UModuls.pas',
  CBD in 'movil\BD\CBD.pas',
  RBD in 'movil\BD\RBD.pas',
  UDaoFactory in 'movil\BD\UDaoFactory.pas',
  UWebServicesImpl in 'movil\WebServices\UWebServicesImpl.pas' {FWebServicesImpl},
  UWebServices in 'movil\WebServices\UWebServices.pas',
  CWebServices in 'movil\WebServices\CWebServices.pas',
  RWebServices in 'movil\WebServices\RWebServices.pas',
  CPrincipal in 'movil\Principal\CPrincipal.pas',
  UContenedorEncabezado in 'movil\Principal\UContenedorEncabezado.pas' {FContenedorEncabezado},
  UContenedorMaestro in 'movil\Principal\UContenedorMaestro.pas' {FContenedorMaestro},
  CContenedorMaestro in 'movil\Principal\CContenedorMaestro.pas',
  TAgenda in 'movil\Agenda\TAgenda.pas',
  RAgenda in 'movil\Agenda\RAgenda.pas',
  CAgenda in 'movil\Agenda\CAgenda.pas',
  cxDrive10 in 'movil\Librerias\cxDrive10.pas',
  UArchivos in 'movil\Librerias\UArchivos.pas',
  TLibrerias in 'movil\Librerias\TLibrerias.pas',
  Sha1 in 'movil\Librerias\Encriptacion\Sha1.pas',
  Twofish in 'movil\Librerias\Encriptacion\Twofish.pas',
  Tools in 'movil\Librerias\Encriptacion\Tools.pas',
  FlipReverseRotateLibrary in 'movil\Librerias\FlipReverseRotateLibrary.pas',
  XUtilerias in 'movil\Librerias\XUtilerias.pas',
  magfmtdisk in 'movil\Librerias\magfmtdisk.pas',
  uLkJSON in 'movil\Librerias\uLkJSON.pas',
  magsubs1 in 'movil\Librerias\magsubs1.pas',
  UAccesoDatos in 'movil\Librerias\UAccesoDatos.pas',
  UZips in 'movil\Librerias\UZips.pas',
  XConstantes in 'movil\Librerias\XConstantes.pas',
  SetupApi in 'movil\Librerias\USB\SetupApi.pas',
  JwaWinBase in 'movil\Librerias\USB\JwaWinBase.pas',
  JwaReason in 'movil\Librerias\USB\JwaReason.pas',
  JwaNtStatus in 'movil\Librerias\USB\JwaNtStatus.pas',
  JwaWinGDI in 'movil\Librerias\USB\JwaWinGDI.pas',
  moduleloader in 'movil\Librerias\USB\moduleloader.pas',
  JwaDbt in 'movil\Librerias\USB\JwaDbt.pas',
  CfgMgr32 in 'movil\Librerias\USB\CfgMgr32.pas',
  WinConvTypes in 'movil\Librerias\USB\WinConvTypes.pas',
  JwaWinNT in 'movil\Librerias\USB\JwaWinNT.pas',
  JwaWinType in 'movil\Librerias\USB\JwaWinType.pas',
  Cfg in 'movil\Librerias\USB\Cfg.pas',
  JwaWinUser in 'movil\Librerias\USB\JwaWinUser.pas',
  JwaWinReg in 'movil\Librerias\USB\JwaWinReg.pas',
  ULibrerias in 'movil\Librerias\ULibrerias.pas',
  MSXML_TLB in 'movil\Librerias\MSXML_TLB.pas',
  UCadenas in 'movil\Librerias\UCadenas.pas',
  UTipos in 'movil\Librerias\UTipos.pas',
  UGenerales in 'movil\Librerias\UGenerales.pas',
  USistema in 'movil\Librerias\USistema.pas',
  UKiosco in 'movil\Librerias\UKiosco.pas',
  MSXML2_TLB in 'movil\Librerias\MSXML2_TLB.pas',
  UParametros in 'movil\Librerias\UParametros.pas',
  UUsb in 'movil\Librerias\UUsb.pas',
  UModulo in 'movil\Librerias\UModulo.pas' {ModuloDatos: TDataModule},
  UVersionUtil in 'movil\Librerias\UVersionUtil.pas',
  TVersionUtil in 'movil\Librerias\TVersionUtil.pas',
  CPropiedades in 'movil\Propiedades\CPropiedades.pas',
  LPropiedades in 'movil\Propiedades\LPropiedades.pas',
  UPropiedades in 'movil\Propiedades\UPropiedades.pas',
  CRegistroCurp in 'movil\Configuracion\CRegistroCurp.pas',
  RRegistroCurp in 'movil\Configuracion\RRegistroCurp.pas',
  TRegistroCurp in 'movil\Configuracion\TRegistroCurp.pas',
  URegistroCurp in 'movil\Configuracion\URegistroCurp.pas' {FRegistroCurp},
  UAvisos in 'movil\Avisos\UAvisos.pas' {FAvisos},
  UAvisosAnteriores in 'movil\Avisos\UAvisosAnteriores.pas' {FAvisosAnteriores},
  UAvisosVisor in 'movil\Avisos\UAvisosVisor.pas' {FAvisosVisor},
  CAvisos in 'movil\Avisos\CAvisos.pas',
  TAvisos in 'movil\Avisos\TAvisos.pas',
  UISelect in 'movil\BD\UISelect.pas',
  UStrHashMap in 'movil\Librerias\UStrHashMap.pas',
  CDescargas in 'movil\Descargas\CDescargas.pas',
  RDescargas in 'movil\Descargas\RDescargas.pas',
  TDescargas in 'movil\Descargas\TDescargas.pas',
  UDescargas in 'movil\Descargas\UDescargas.pas' {FDescargas},
  UHashMap in 'movil\Librerias\UHashMap.pas',
  RTemas in 'movil\Temas\RTemas.pas',
  UDialogoMensaje in 'movil\Librerias\UDialogoMensaje.pas' {FDialogoMensaje},
  TPrincipal in 'movil\Principal\TPrincipal.pas',
  URestauracionWeb in 'movil\Restauracion\URestauracionWeb.pas' {FRestauracionWeb},
  CRestauracionWeb in 'movil\Restauracion\CRestauracionWeb.pas',
  RRestauracionWeb in 'movil\Restauracion\RRestauracionWeb.pas',
  UMcc in 'movil\Utilerias\UMcc.pas',
  RRespaldos in 'movil\Respaldos\RRespaldos.pas',
  UHilos in 'movil\Librerias\UHilos.pas',
  CEnvios in 'movil\Envios\CEnvios.pas',
  REnvios in 'movil\Envios\REnvios.pas',
  UEnvios in 'movil\Envios\UEnvios.pas' {FEnvios},
  UEnviosDatos in 'movil\Envios\UEnviosDatos.pas',
  UEnviosFiltro in 'movil\Envios\UEnviosFiltro.pas' {FEnviosFiltro},
  TEnvios in 'movil\Envios\TEnvios.pas',
  UProcesosSP in 'movil\Principal\UProcesosSP.pas',
  UUtileriasTablas in 'movil\Utilerias\UUtileriasTablas.pas',
  UVisitas in 'movil\Visitas\UVisitas.pas' {FVisitas},
  UVisitasAgregar in 'movil\Visitas\UVisitasAgregar.pas' {FVisitasAgregar},
  CVisitas in 'movil\Visitas\CVisitas.pas',
  TVisitas in 'movil\Visitas\TVisitas.pas',
  RVisitas in 'movil\Visitas\RVisitas.pas',
  UEstatus in 'movil\Visitas\UEstatus.pas',
  TMovimientos in 'movil\Visitas\TMovimientos.pas',
  UNavegador in 'movil\Navegador\UNavegador.pas' {FNavegador},
  UCierre in 'movil\Cierre\UCierre.pas',
  TCierre in 'movil\Cierre\TCierre.pas',
  TWebServices in 'movil\WebServices\TWebServices.pas',
  IEnvios in 'movil\Envios\IEnvios.pas',
  CActualizacion in 'movil\Actualizacion\CActualizacion.pas',
  RActualizacion in 'movil\Actualizacion\RActualizacion.pas',
  TActualizacion in 'movil\Actualizacion\TActualizacion.pas',
  UActualizacion in 'movil\Actualizacion\UActualizacion.pas' {FActualizacion},
  CCargarCuestionario in 'movil\Cuestionario\CCargarCuestionario.pas',
  TCargarCuestionario in 'movil\Cuestionario\TCargarCuestionario.pas',
  UCargarCuestionario in 'movil\Cuestionario\UCargarCuestionario.pas' {FCargarCuestionario},
  UExportar in 'movil\Cuestionario\UExportar.pas' {FExportar},
  UInterfaceInterprete in 'movil\Cuestionario\UInterfaceInterprete.pas',
  UInterpreteFactory in 'movil\Cuestionario\UInterpreteFactory.pas',
  UUtileriasCuestionarios in 'movil\Cuestionario\UUtileriasCuestionarios.pas',
  CManualesFiltro in 'movil\Manuales\CManualesFiltro.pas',
  RManualesFiltro in 'movil\Manuales\RManualesFiltro.pas',
  TManualesFiltro in 'movil\Manuales\TManualesFiltro.pas',
  UManualesFiltro in 'movil\Manuales\UManualesFiltro.pas' {FManualesFiltro},
  UManualesPantalla in 'movil\Manuales\UManualesPantalla.pas' {FManualesPantalla},
  UPantallaCompleta in 'movil\Manuales\UPantallaCompleta.pas' {FPantallaCompleta},
  UInformacion in 'movil\Ingreso\UInformacion.pas' {FInformacion},
  UEnviosDetalle in 'movil\Envios\UEnviosDetalle.pas' {FEnviosDetalle},
  UFtp in 'movil\Librerias\UFtp.pas' {FFtp},
  URegistroDetalle in 'movil\Configuracion\URegistroDetalle.pas' {FRegistroDetalle},
  AcroPDFLib_TLB in 'movil\Librerias\AcroPDFLib_TLB.pas' {$R *.res},
  UCroquis in 'movil\Croquis\UCroquis.pas' {FCroquis},
  UCargarParametros in 'movil\Cuestionario\UCargarParametros.pas' {FCargarParametros},
  UActualizacionDetalle in 'movil\Actualizacion\UActualizacionDetalle.pas' {FActualizacionDetalle},
  UPaginacion in 'movil\Utilerias\UPaginacion.pas' {FPaginacion},
  UDmlAbstract in 'movil\Xml\UDmlAbstract.pas',
  UTransparenteCierre in 'movil\Cierre\UTransparenteCierre.pas' {FTransparenteCierre},
  UCredenciales in 'movil\Kiosco\UCredenciales.pas' {FCredenciales},
  URescate in 'movil\Ingreso\URescate.pas' {FRescate},
  UAgendaAcciones in 'movil\Agenda\UAgendaAcciones.pas' {FAgendaAcciones},
  UAgendaX in 'movil\Agenda\UAgendaX.pas' {FAgendaX},
  TBitacorasWeb in 'movil\Librerias\TBitacorasWeb.pas',
  UCargarSQL in 'movil\BD\UCargarSQL.pas' {FCargarSQL},
  TCargarSQL in 'movil\BD\TCargarSQL.pas',
  UActivarCuenta in 'movil\Ingreso\UActivarCuenta.pas' {FActivarCuenta},
  UExportarInterprete in 'movil\Cuestionario\UExportarInterprete.pas' {FExportarInterprete},
  USeguridad in 'movil\Librerias\USeguridad.pas',
  USeleccionProyecto in 'movil\Cuestionario\USeleccionProyecto.pas' {FSeleccionProyecto},
  UCargarCuestionarioMovil in 'movil\Cuestionario\UCargarCuestionarioMovil.pas' {FCargarCuestionarioMovil},
  CGeo in 'movil\Geo\CGeo.pas',
  RGeo in 'movil\Geo\RGeo.pas',
  UGeo in 'movil\Geo\UGeo.pas' {FGeo},
  UNotasX in 'movil\Notas\UNotasX.pas' {FNotasX},
  CNotasX in 'movil\Notas\CNotasX.pas',
  RNotasX in 'movil\Notas\RNotasX.pas',
  TNotasX in 'movil\Notas\TNotasX.pas',
  UNotasAccionesX in 'movil\Notas\UNotasAccionesX.pas' {FNotasAccionesX},
  SevenZipVCL in 'movil\Librerias\SevenZipVCL.pas',
  UMasterZip in 'movil\Librerias\UMasterZip.pas',
  USevenZip in 'movil\Librerias\USevenZip.pas',
  UAlertaBateria in 'movil\Principal\UAlertaBateria.pas' {FAlertaBateria},
  UIncidencias in 'movil\Incidencias\UIncidencias.pas' {FIncidencia},
  CBateria in 'movil\Bateria\CBateria.pas',
  RBateria in 'movil\Bateria\RBateria.pas',
  TBateria in 'movil\Bateria\TBateria.pas',
  UPrincipalEnvipe in 'envipe\Principal\UPrincipalEnvipe.pas' {FPrincipalEnvipe},
  CLevantamiento in 'envipe\Levantamiento\CLevantamiento.pas',
  RLevantamiento in 'envipe\Levantamiento\RLevantamiento.pas',
  TDuplicarHogares in 'envipe\Levantamiento\TDuplicarHogares.pas',
  TLevantamiento in 'envipe\Levantamiento\TLevantamiento.pas',
  UAccesoSemaforos in 'envipe\Levantamiento\UAccesoSemaforos.pas',
  UCambiaSemaforos in 'envipe\Levantamiento\UCambiaSemaforos.pas' {FCambiaSemaforos},
  UCierreEnvipe in 'envipe\Levantamiento\UCierreEnvipe.pas',
  UCroquisEnvipe in 'envipe\Levantamiento\UCroquisEnvipe.pas' {FCroquisEnvipe},
  ULevantamiento in 'envipe\Levantamiento\ULevantamiento.pas' {FLevantamiento},
  ULevantamientoDetalle in 'envipe\Levantamiento\ULevantamientoDetalle.pas' {FLevantamientoDetalle},
  UNumeroHogares in 'envipe\Levantamiento\UNumeroHogares.pas' {FNumeroHogares},
  UPresencia in 'envipe\Levantamiento\UPresencia.pas' {FPresencia},
  USeleccionInstrumento in 'envipe\Levantamiento\USeleccionInstrumento.pas' {FSeleccionInstrumento},
  UVerificacion in 'envipe\Levantamiento\UVerificacion.pas' {FVerificacion},
  CEstatusEnvipe in 'envipe\Utilerias\CEstatusEnvipe.pas',
  CUtileriasEnvipe in 'envipe\Utilerias\CUtileriasEnvipe.pas',
  REstatusEnvipe in 'envipe\Utilerias\REstatusEnvipe.pas',
  RUtileriasEnvipe in 'envipe\Utilerias\RUtileriasEnvipe.pas',
  UGeneralesEnvipe in 'envipe\Utilerias\UGeneralesEnvipe.pas',
  UUtileriasEnvipe in 'envipe\Utilerias\UUtileriasEnvipe.pas',
  UDesplazamientoSeleccionado in 'envipe\Levantamiento\Hogar\Seleccionado\UDesplazamientoSeleccionado.pas' {FDesplazamientoSeleccionado},
  UEncuentraSeleccionado in 'envipe\Levantamiento\Hogar\Seleccionado\UEncuentraSeleccionado.pas' {FEncuentraSeleccionado},
  UHogarSeleccionado in 'envipe\Levantamiento\Hogar\Seleccionado\UHogarSeleccionado.pas' {FHogarSeleccionado},
  TVictimizacion in 'envipe\Levantamiento\Hogar\Seleccionado\Victimizacion\TVictimizacion.pas',
  UJustificaVictimizacion in 'envipe\Levantamiento\Hogar\Seleccionado\Victimizacion\UJustificaVictimizacion.pas' {FJustificacion},
  USeleccionadoVictimizacion in 'envipe\Levantamiento\Hogar\Seleccionado\Victimizacion\USeleccionadoVictimizacion.pas' {FSeleccionadoVictimizacion},
  UAgendaEnvipe in 'envipe\Agenda\UAgendaEnvipe.pas' {FAgendaEnvipe},
  CInterpreteCuestionario in 'envipe\Cuestionarios\CInterpreteCuestionario.pas',
  RInterpreteCuestionario in 'envipe\Cuestionarios\RInterpreteCuestionario.pas',
  UExportarEnvipe in 'envipe\Cuestionarios\UExportarEnvipe.pas' {FExportarEnvipe},
  UInterpreteEnvipe in 'envipe\Cuestionarios\UInterpreteEnvipe.pas',
  TEnviosEnvipe in 'envipe\Envios\TEnviosEnvipe.pas',
  UEnvioFiltroEnvipe in 'envipe\Envios\UEnvioFiltroEnvipe.pas' {FEnvioFiltroEnvipe},
  UEnviosEnvipe in 'envipe\Envios\UEnviosEnvipe.pas',
  UEnviosFiltroEnvipe in 'envipe\Envios\UEnviosFiltroEnvipe.pas',
  UNotasEnvipe in 'envipe\Notas\UNotasEnvipe.pas' {FNotasEnvipe},
  CSupervision in 'envipe\Supervision\CSupervision.pas',
  TReporte in 'envipe\Supervision\TReporte.pas',
  TSupervision in 'envipe\Supervision\TSupervision.pas',
  TVerificacionSP in 'envipe\Supervision\TVerificacionSP.pas',
  UAccionSupervision in 'envipe\Supervision\UAccionSupervision.pas' {FAccionSupervision},
  UReporte in 'envipe\Supervision\UReporte.pas' {FReporte},
  USeguimiento in 'envipe\Supervision\USeguimiento.pas' {FSeguimiento},
  USupervision in 'envipe\Supervision\USupervision.pas' {FSupervision},
  UVerificacionSP in 'envipe\Supervision\UVerificacionSP.pas' {FVerificacionSP},
  TVisitasEnvipe in 'envipe\Visitas\TVisitasEnvipe.pas',
  UVisitasEnvipe in 'envipe\Visitas\UVisitasEnvipe.pas' {FVisitasEnvipe},
  UVisitasEnvipeAgregar in 'envipe\Visitas\UVisitasEnvipeAgregar.pas' {FVisitasEnvipeAgregar},
  ULevantamientoHogar in 'envipe\Levantamiento\Hogar\ULevantamientoHogar.pas' {FLevantamientoHogar},
  TCambio in 'movil\Seleccionado\TCambio.pas',
  UCambio in 'movil\Seleccionado\UCambio.pas' {FCambio};

{$R *.res}
{$R *.TLB}
{$R 'imagenMsn.res' 'imagenMsn.rc'}

var
  ruta              : WideString;
  directorioRecursos: PWideChar;
begin
  Application.Initialize;
  ruta              := ExtractFilePath(Application.ExeName)+ 'recursos';
  directorioRecursos:= Addr(ruta[1]);
  SetDllDirectory(directorioRecursos);
  FEntrada:= TFEntrada.Create(application);
  FEntrada.Show;
  FEntrada.Update;
	Application.MainFormOnTaskbar := True;
	Application.CreateForm(TFPrincipalEnvipe, FPrincipalEnvipe);
  FEntrada.hide;
	freeAndNil(FEntrada);
  try
		try
      WaitStart('Cargando cuestionarios');
      TInterpreteEnvipe.getInstance.crearInterprete;
      WaitEnd;
      generales.NOTAS_PRINCIPAL:= TFNotasEnvipe;
      generales.AGENDA_PRINCIPAL := TFAgendaEnvipe;
			if TFIngreso.execute(FPrincipalEnvipe) then begin
				Application.run;
			end; // if TFIngreso
		except
			on e: exception do
				TLogger.getInstance.error('[Movil.Main] '+ e.message);
		end; // try - except
	finally
		TLogger.getInstance.error('[Movil.Main] se procede a liberar instancia de interprete');
    //TInterpreteEnvipe.getInstance.liberaInterprete;
    //TInterpreteEnvipe.getInstance.destroy;
		TLogger.getInstance.error('[Movil.Main] Finaliza la liberacion de instancias de interprete');
  end; // try - finally
end.
