delete from TC_CLAVES_OPERATIVAS;
delete from TR_MOVIL_AGENDAS;
delete from TC_MUESTRAS;	
delete from TR_MOVIL_FOTOGRAFIAS_ENVIOS;
delete from TR_MOVIL_VISITAS_DETALLE;
delete from TR_MOVIL_VISITAS;
delete from TR_MOVIL_ACCESOS;
delete from TR_MOVIL_DESCARGAS;
delete from TR_MOVIL_DESCARGAS_MOV;
delete from TR_MOVIL_ENVIOS_WEB;
delete from TR_MOVIL_ENVIOS_WEB_MOV;
delete from TR_MOVIL_RESPALDOS;
delete from TR_MOVIL_SENTENCIAS;
delete from TR_MOVIL_WS_BITACORA;
delete from TR_MOVIMIENTOS;
delete from TR_MOVIL_NOTAS;
delete from TR_MOVIL_AVISOS;
delete from TR_envipe2023_MUESTRAS;
delete from TR_envipe2023_VISITAS;
delete from TR_envipe2023_VIC_JUSTIFICA;
delete from TR_envipe2023_VICTIMIZACIONES;
delete from tr_envipe2023_eleg;
delete from tr_envipe2023_eleg_ap4_8;
delete from tr_envipe2023_eleg_ap5_3;
delete from tr_envipe2023_eleg_ap6_10;
delete from tr_envipe2023_eleg_ap6_15;
delete from tr_envipe2023_eleg_ap6_20;
delete from tr_envipe2023_eleg_ap6_4;
delete from tr_envipe2023_eleg_ap7_3;
delete from tr_envipe2023_eleg_obs;
delete from tr_envipe2023_modulo;
delete from tr_envipe2023_modulo_c;
delete from tr_envipe2023_modulo_obs;
delete from tr_envipe2023_sdg;
delete from tr_envipe2023_sdg_int;
delete from tr_envipe2023_sdg_obs;
delete from tr_envipe2023_vvda;
delete from tr_envipe2023_vvda_obs;
delete from TR_MOVIL_BIT_VERIFICACION;
delete from TR_RESULTADOS_SUP;							  
delete from tr_movil_bit_cierres;
delete from TR_MOVIL_USUARIOS where num_emp not like 'X%';
update tc_movil_configuraciones set acceso_cierre=3;
update TR_MOVIL_USUARIOS set activo=1 where num_emp  like 'X%';
update tc_movil_configuraciones set registrado=0, clave_guid=null, clave=null, id_clave_operativa=null, semilla=null, id_entidad_oficina=null, co_estatal = null, NOMBRE_EQUIPO = null;
delete from tr_movil_actualizaciones where id_movil_actualizacion =(select id_movil_actualizacion from (select min(version_anterior), id_movil_actualizacion from tr_movil_actualizaciones));
insert into tr_movil_avisos(id_movil_aviso, id_movil_estatus_aviso, num_emp, id_aviso_movil_det, mensaje,  registro_publicacion, consecutivo, version) values (111111,	2,	'X1000',	0,	'Bienvenido al nuevo Iktan, mas seguro e intuitivo, con mejor rendimiento y caracteristicas que haran tu trabajo mas sencillo en toda tu jornada laboral. Nuestro compromiso por entregar un sistema de calidad va dirigido a ti.',		'20150414132645111',	1,	'0001');